# Generated by Django 5.2.6 on 2025-09-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_target_amount_project_total_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='current_fundraising',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
