# Generated by Django 5.2.6 on 2025-09-20 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_project_current_fundraising'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='current_fundraising',
        ),
    ]
