# Generated by Django 5.2.6 on 2025-09-20 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_project_current_fundraising'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
